### ISSUE TITLE
Various comments

### ISSUE THREAD

**Issue by Dolgubon** [rp12439/crafty#10]
https://github.com/rp12439/crafty/blob/a7884ee195ecc33eec8ecb6dd13859c7d7d449f7/Crafty.lua#L330
You could put the labels into a table for using it in a loop, so you don't have to write it out 7 times.
Another option would be do something like CraftyStockListType:GetChild(1):GetNamedChild("Label"):SetColor()

https://github.com/rp12439/crafty/blob/a7884ee195ecc33eec8ecb6dd13859c7d7d449f7/Crafty.lua#L46
You probably don't need to make all these copies of the saved vars, and can instead modify them directly. Also, the watchlist stuff could be done more programatically:

e.g.
for i = 1, # Crafty.savedVariables.WatchLists do
-- do stuff with Crafty.savedVariables.WatchLists[i] 
end

It would also make it easier if you wanted to in the future make it possible to have more watchlists

**Comment by rp12439** [comment]
Thanks a lot!

I opened enhancement issues
